name: quick_bites
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"   # Dart 3.x compatible with null safety

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  # curved_navigation_bar: ^1.0.3   # curved nav bar package
  delightful_toast: ^1.1.0
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.5.3
  lucide_icons: ^0.257.0
  flutter_launcher_icons: ^0.14.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    

  fonts:
    - family: Screen
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 900


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/images/qb.png"
  adaptive_icon_background: "#ffffff"
  # adaptive_icon_foreground: "assets/icon_foreground.png"
